networks:
  # Make sure this newtwork exists before runtime. `create-plex-stack-networks.sh`
  plex_stack_backend:
    external: true
      
services:
  TEMPLATE_NAME:
    container_name: $NAME
    hostname: $NAME
    restart: $RESTART
    image: $IMAGE
    volumes:
      - ${CONFIG_DIR}:/config
      - ${CONTAINER_DATA_DIR}:/data
      - ${MEDIA_DATA_DIR}:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: "backend"
      traefik.http.routers.TEMPLATE_NAME.rule: "Host(`${NAME}.${DOMAIN_NAME}`)"
      traefik.http.routers.TEMPLATE_NAME.entrypoints: "https"
      traefik.http.routers.TEMPLATE_NAME.tls: "true"
      traefik.http.routers.TEMPLATE_NAME.tls.certresolver: "le"
      # Swarm Mode
      #traefik.http.services.TEMPLATE_NAME.loadbalancer.server.port: "$PORT"
    networks:
      plex_stack_backend:
